# ETAPA 1: Construcción
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

# 1. Copiamos el archivo de solución
COPY REST_GestionUsuarios.sln ./

# 2. CREAMOS las carpetas para que coincidan con la estructura del SLN
# Y copiamos los archivos .csproj individualmente
COPY REST_GestionUsuarios/REST_GestionUsuarios.csproj ./REST_GestionUsuarios/
COPY REST_GestionUsuarios.Tests/REST_GestionUsuarios.Tests.csproj ./REST_GestionUsuarios.Tests/

# 3. Ahora el restore encontrará todos los proyectos mencionados en el .sln
RUN dotnet restore

# 4. Copiamos el resto del código fuente
COPY . .

# 5. Publicamos la API
WORKDIR "/src/REST_GestionUsuarios"
RUN dotnet publish -c Release -o /app/publish /p:UseAppHost=false

# ETAPA 2: Ejecución
FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
EXPOSE 8080
EXPOSE 80

COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "REST_GestionUsuarios.dll"]