# ETAPA 1: Compilación (La llamamos 'compilacion' para evitar errores circulares)
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS compilacion
WORKDIR /src

# Copiamos archivos de la solución y proyectos
COPY REST_GestionUsuarios.sln ./
COPY REST_GestionUsuarios/REST_GestionUsuarios.csproj ./REST_GestionUsuarios/
COPY REST_GestionUsuarios.Tests/REST_GestionUsuarios.Tests.csproj ./REST_GestionUsuarios.Tests/

# Restauramos dependencias
RUN dotnet restore

# Copiamos todo el código (Aquí entra la carpeta Infraestructure)
COPY . .

# Publicamos la aplicación
WORKDIR "/src/REST_GestionUsuarios"
RUN dotnet publish -c Release -o /app/out /p:UseAppHost=false


# ETAPA 2: Ejecución (Runtime)
FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app

# Instalación de dependencias de Oracle para Linux
USER root
RUN apt-get update && apt-get install -y --no-install-recommends libaio1 && \
    rm -rf /var/lib/apt/lists/*

# Parches de seguridad OpenSSL
RUN sed -i 's/MinProtocol = TLSv1.2/MinProtocol = TLSv1.1/g' /etc/ssl/openssl.cnf && \
    sed -i 's/CipherString = DEFAULT@SECLEVEL=2/CipherString = DEFAULT@SECLEVEL=1/g' /etc/ssl/openssl.cnf

# COPIA CRÍTICA: Traemos los archivos de la etapa 'compilacion'
COPY --from=compilacion /app/out .

# Verificamos si la carpeta existe (Si el .csproj está bien, esto no fallará)
RUN ls -R /app/Infraestructure/OracleWallet || echo "La carpeta no está en la raíz, buscando..."

ENV ASPNETCORE_URLS=http://+:8080
EXPOSE 8080

ENTRYPOINT ["dotnet", "REST_GestionUsuarios.dll"]