# ETAPA 1: Construcción
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

# Como el contexto ahora es la carpeta Taller_REST_API, el SLN está en la raíz del contexto
COPY *.sln .

# Copiamos el proyecto. 
# Basado en tu captura, dentro de la carpeta Taller_REST_API hay OTRA carpeta Taller_REST_API
COPY Taller_REST_API/*.csproj ./Taller_REST_API/

# Restauramos
RUN dotnet restore

# Copiamos todo lo demás
COPY . .

# Publicamos
WORKDIR "/src/Taller_REST_API"
RUN dotnet publish -c Release -o /app/publish /p:UseAppHost=false

# ETAPA 2: Ejecución
FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
EXPOSE 8080
EXPOSE 80

COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "Taller_REST_API.dll"]